spring:
  application:
    name: customer-service  # 建議小寫，避免潛在問題
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        health-check-path: /actuator/health
        health-check-interval: 30s
    openfeign:
      circuitbreaker:
        enabled: true
resilience4j:
  circuitbreaker:
    instances:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000ms
        permittedNumberOfCallsInHalfOpenState: 3
  retry:
    instances:
      default:
        maxAttempts: 3
        waitDuration: 500ms
management:
  endpoints:
    web:
      exposure:
        include: health,info
server:
  port: 8081