services:
  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - "2181:2181"
    volumes:
      - zookeeper_data:/bitnami/zookeeper

  kafka:
    image: wurstmeister/kafka:latest
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_NUM_PARTITIONS: 1
    ports:
      - "9093:9093"
    volumes:
      - kafka_data:/kafka
    depends_on:
      - zookeeper

  consul:
    image: hashicorp/consul:1.20  # 改為 1.20 版本
    ports:
      - "8500:8500"  # Consul UI 和 HTTP API
      - "8600:8600/udp"  # DNS 服務
    volumes:
      - consul_data:/consul/data
    command: "agent -server -bootstrap-expect=1 -ui -client=0.0.0.0"

  zipkin:
    image: openzipkin/zipkin:latest
    environment:
      STORAGE_TYPE: mem  # 使用記憶體儲存
      KAFKA_BOOTSTRAP_SERVERS: kafka:9093  # 連接到 Kafka
    ports:
      - "9411:9411"  # Zipkin UI 和 API
    depends_on:
      - kafka

volumes:
  zookeeper_data:
  kafka_data:
  consul_data:
